baseURL: https://ravenlabs.dev
languageCode: en-us
title: Raven Labs
theme: vanilla
staticDir:
- static
  #googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Secure Phones
    pre: smartphone
    url: /secure-phones/
    weight: 2
  - name: Minecraft
    pre: box
    url: /minecraft/
    weight: 3
  - name: Websites
    pre: monitor
    url: /websites/
    weight: 4
  - name: Contact
    pre: message-square
    url: /contact/
    weight: 5

params:
  includeBootstrapJs: false
  logo: /logo.png
  showActiveNav: false
  containerMaxWidth: 70em
  logoMaxWidth: 70%
  dateFormat: Jan 2, 2006
  homeText: For your web development, cybersecurity and game server needs.
  footerText: © Copyright 2021 Raven Labs Limited
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
  
deployment:
  targets:
    - name: "production"
      URL: "s3://ravenlabs.dev?region=eu-west-1"
