# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy site
        uses: AlbertMorenoDEV/deploy-hugo-to-s3-action@v0.0.3
        with:
          hugo-version: 0.89.0
          target: production
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

